#!/bin/bash

# Omega Dijital Bakım Komutları
# Production için sık kullanılan komutlar

echo "🔧 Omega Dijital Bakım Komutları"
echo "================================"

echo ""
echo "🚀 Servis Yönetimi"
echo "------------------"
echo "# Uygulama yeniden başlat"
echo "pm2 restart omega-api"
echo ""
echo "# PM2 durum kontrolü"
echo "pm2 status"
echo ""
echo "# PM2 log'ları izle"
echo "pm2 logs omega-api --lines 100 --follow"
echo ""
echo "# PM2 monitör"
echo "pm2 monit"

echo ""
echo "🔄 Kod Deploy"
echo "-------------"
echo "# Yeni kod çek"
echo "cd /home/omega/omega && git pull"
echo ""
echo "# Backend build"
echo "cd backend && npm run build"
echo ""
echo "# Servis restart"
echo "pm2 restart omega-api"
echo ""
echo "# Frontend build"
echo "cd ../frontend && npm run build"
echo "# (Nginx static dosyaları otomatik servis eder)"

echo ""
echo "🗄️  Veritabanı Yönetimi"
echo "----------------------"
echo "# DB backup"
echo "pg_dump -U omega omega_db > backup_\$(date +%Y%m%d).sql"
echo ""
echo "# DB restore"
echo "psql -U omega omega_db < backup_YYYYMMDD.sql"
echo ""
echo "# DB bağlantı test"
echo "psql -U omega -d omega_db -h localhost -c 'SELECT 1;'"

echo ""
echo "🔴 Redis Yönetimi"
echo "----------------"
echo "# Redis durum"
echo "redis-cli ping"
echo ""
echo "# Redis log'ları"
echo "sudo tail -f /var/log/redis/redis-server.log"
echo ""
echo "# Redis restart"
echo "sudo systemctl restart redis"

echo ""
echo "🌐 Nginx Yönetimi"
echo "-----------------"
echo "# Nginx durum"
echo "sudo systemctl status nginx"
echo ""
echo "# Nginx restart"
echo "sudo systemctl restart nginx"
echo ""
echo "# Nginx config test"
echo "sudo nginx -t"
echo ""
echo "# Nginx log'ları"
echo "sudo tail -f /var/log/nginx/omega-cms-access.log"
echo "sudo tail -f /var/log/nginx/omega-cms-error.log"

echo ""
echo "🔒 Güvenlik Yönetimi"
echo "-------------------"
echo "# Fail2ban durumu"
echo "sudo fail2ban-client status"
echo ""
echo "# Banlı IP'leri göster"
echo "sudo fail2ban-client status sshd"
echo ""
echo "# IP ban'ı kaldır"
echo "sudo fail2ban-client set sshd unbanip IP_ADRESI"
echo ""
echo "# Firewall durumu"
echo "sudo ufw status verbose"

echo ""
echo "📊 Sistem İzleme"
echo "---------------"
echo "# Sistem yükü"
echo "uptime"
echo ""
echo "# Disk kullanımı"
echo "df -h"
echo ""
echo "# RAM kullanımı"
echo "free -h"
echo ""
echo "# Process list"
echo "ps aux | head -20"

echo ""
echo "🔧 Sistem Bakımı"
echo "---------------"
echo "# Sistem güncellemeleri"
echo "sudo apt update && sudo apt upgrade -y"
echo ""
echo "# Paket temizliği"
echo "sudo apt autoremove && sudo apt autoclean"
echo ""
echo "# Log temizliği (son 7 gün)"
echo "sudo find /var/log -name '*.log' -mtime +7 -delete"
echo ""
echo "# PM2 log temizliği"
echo "pm2 flush"

echo ""
echo "🔒 SSL Yönetimi"
echo "---------------"
echo "# SSL sertifikası yenile"
echo "sudo certbot renew"
echo ""
echo "# SSL yenileme test"
echo "sudo certbot renew --dry-run"
echo ""
echo "# SSL expiry kontrolü"
echo "echo | openssl s_client -servername DOMAIN -connect DOMAIN:443 2>/dev/null | openssl x509 -noout -enddate"

echo ""
echo "🚨 Acil Durum Komutları"
echo "---------------------"
echo "# Tüm servisleri restart et"
echo "pm2 restart all && sudo systemctl restart nginx && sudo systemctl restart redis"
echo ""
echo "# Sistem reboot"
echo "sudo reboot"
echo ""
echo "# Acil log kontrolü"
echo "sudo journalctl -xe --no-pager"

echo ""
echo "📋 Örnek Bakım Schedule"
echo "-----------------------"
echo "# Haftalık (Pazar 02:00)"
echo "0 2 * * 0 /home/omega/backup-db.sh"
echo ""
echo "# Günlük (03:00)"
echo "0 3 * * * /usr/bin/certbot renew --quiet"
echo ""
echo "# Aylık (1. gün 04:00)"
echo "0 4 1 * * /home/omega/monthly-maintenance.sh"
